// Questions
var q = [
	'What do you do?',
	'What do you do, 30 seconds',
	'How big is the opportunity?',
	'Who are you customers?',
	'Give me more insights about you users',
	'What do you do?',
	'Why did you chose this idea?',
	'Are you open to change your idea?',
	'Where users come from?',
	'Who needs it?',
	'How do you know they need it? ',
	'How do you know people want this?',
	'What do you understand about your users?',
	'What are they doing now?',
	'What resistance they have to trying you and how you overcome it?.',
	'What have you learned so far from working on it?',
	'What makes new users try you?',
	'Why reluctant users hold back from buying?',
	'What are the top things users want?',
	'What have surprised you about user behavior?',
	'How are you meeting your customers?',
	'How you understanding customer needs?',
	'How big an opportunity is there?',
	'Who are you competitors?',
	'How does your unit econ work?',
	'What exactly makes you different from the other options?',
	'What do you know that other don&#39;t?',
	'How is your product different?',
	'Why would you be worth 1 Billion dollars. Market Size?',
	'What&#39;s new about what you make?',
	'What competition do you fear the most?',
	'Who might become competitors?',
	'Why will you succeed?',
	'What are you going to do next?',
	'How much money could you make per year?',
	'What&#39;s the thing about you business outsiders don&#39;t understand',
	'Why nobody has done this?',
	'If your startup succeeds, what other areas might you be able to expand to?',
	'Why isn&#39;t somebody using this?',
	'Someone just showed me an idea just like yours, I don&#39;t like it. What else do you have?',
	'Why you margins are so low?',
	'What obstacles do you face and how to overcome them?',
	'What problems/hurdles are you anticipating?',
	'6 Months from know, what&#39;s your biggest problem?',
	'Tell us about a tough problem you solved it',
	'Why did your team get together?',
	'What will you do if we don&#39;t fund you?',
	'What&#39;s the worst thing that has happened?',
	'What&#39;s your user growth rate?',
	'What are you working on?',
	'What&#39;s your distribution strategy?',
	'What&#39;s the next step in you product evolution?',
	'Where is the rocket science in here?',
	'What are you going to do next?',
	'How does the subscription works?',
	'How users find about you?',
	'What&#39;s the conversion rate?',
	'How long can you go before funding?',
	'Have you raised funding?',
	'What would you do if we don&#39;t fund you?',
	'What&#39;s your exit strategy?',
	'Who will be your next hire?',
	'Who in your team does what?',
	'What systems have you hacked?',
	'Most impressive thing you have done?',
	'Who is the boss?',
	'Will your team Stick at this?',
	'How do we know the team will stick together?',
	'What else have you created together?',
	'In what ways are you resourceful?',
	'What domain expertise you have?',
	'What&#39;s the biggest mistake you have made?',
	'What&#39;s the funniest thing that happened to you?',
	'What makes you special?',
	'What&#39;s your secret sauce?',
	'How did your team meet?',
	'Tell us about a tough problem you solved it?',
	'How did you decided who was going to be the CEO?',
	'How do you complement each other?',
	'Why you, Antonio?'
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];
